Issue/#2  setup styled components theming
thecodeclimber/bluejay-redparts pull request #16
Opened 2021-02-12 12:27 UTC by lokesh75way

2021-02-15 06:08 UTC, thecodeclimber requested changes

2021-02-15 06:08 UTC, thecodeclimber commented on package.json
> +    "path": "^0.12.7",
Why do we need `path`?   Where do we use it?

2021-02-15 06:08 UTC, thecodeclimber commented on src/components/Layout.tsx
> +import Theme from './Theme';
In the `next.js` example, they use the `ThemeProvider` in `_app.js`.  Let's do the same.

Here is the link: https://github.com/vercel/next.js/blob/canary/examples/with-styled-components/pages/_app.js

2021-02-15 06:08 UTC, thecodeclimber commented on src/components/Layout.tsx
> +interface Props extends PropsWithChildren<{}> {}
What is this for?

2021-02-15 06:08 UTC, thecodeclimber commented on theme.ts
> +const theme: DefaultTheme = {
Why do we have both a `theme.ts` file and a `Theme.tsx` file?  

We should have only one file -- as follows:

* Create a `theme` folder in `src`.
* Put `Theme.tsx` inside the `theme` folder
* Create a `GlobalStyles.tsx` file inside of the `theme` folder (we'll add styles there later on).
* Make sure to import the `Theme.jsx` and `GlobalStyles.tsx` inside of `_app.js` as shown in the `next.js` example:  https://github.com/vercel/next.js/blob/canary/examples/with-styled-components/pages/_app.js

Thanks.

2021-02-15 12:37 UTC, lokesh75way commented on package.json
> +    "path": "^0.12.7",
This `issue/#2--setup-styled-components-theming` is created from branch `issue/#1--setup-styled-components`(because of it's dependency)
and path is present in `issue/#1--setup-styled-components` branch, Now I updated this PR for `issue/#1--setup-styled-components` instead of `develop` branch.

2021-02-15 12:37 UTC, lokesh75way commented on src/components/Layout.tsx
> +interface Props extends PropsWithChildren<{}> {}
reverted

2021-02-15 12:40 UTC, lokesh75way commented on src/components/Layout.tsx
> +import Theme from './Theme';
noted

2021-02-15 12:40 UTC, lokesh75way commented on theme.ts
> +const theme: DefaultTheme = {
noted

2021-02-16 12:38 UTC, thecodeclimber requested changes

2021-02-16 12:38 UTC, thecodeclimber commented on src/theme/Theme.tsx
> +  return <ThemeProvider theme={theme}>{children}</ThemeProvider>;
Please move `ThemeProvider` to `_app.js`.  I want to separate `ThemeProvider` from the `Theme.jsx` file.  Thanks.

2021-02-16 12:38 UTC, thecodeclimber commented on src/pages/_app.tsx
> +        <Theme>
see comment below on moving `ThemeProvider`

2021-02-16 12:38 UTC, thecodeclimber commented on styled.declare.ts
> +}
Isn't this repetitive?  I believe this is related to typescript (which I have never used).  Nonetheless, does typescript require that we declare the theme twice?  I hope not -- either way, we need to keep this DRY and only declare the theme properties once.

2021-02-16 12:40 UTC, thecodeclimber commented on package.json
> +    "path": "^0.12.7",
@lokesh75way

Okay -- but I still don't understand why we need this.  Where do we use it? Can you point to me a file that uses this package?  Thanks.

2021-02-17 13:59 UTC, lokesh75way commented on src/theme/Theme.tsx
> +  return <ThemeProvider theme={theme}>{children}</ThemeProvider>;
Noted

2021-02-17 13:59 UTC, lokesh75way commented on src/pages/_app.tsx
> +        <Theme>
Ok

2021-02-17 14:00 UTC, lokesh75way commented on styled.declare.ts
> +}
Deleted styled.declare.ts file and created interface (DefaultTheme) into Theme.jsx.

2021-02-17 23:05 UTC, merged